name: Setup Node.js
description: Reusable action to setup Node.js

inputs:
  node-version:
    required: false
    description: "version of Node.js to use"
  os:
    required: false
    description: "os to use"
  skip-install:
    required: false
    description: "whether to skip pnpm install && pnpm build"
  after-build:
    required: false
    description: "additional steps to run"
runs:
  using: "composite"
  steps:
    - name: Use Node ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        check-latest: true
    - name: Enable pnpm
      shell: bash
      run: corepack enable && pnpm --version
    - name: Get pnpm store path
      id: get-store-path
      shell: bash
      run: echo STORE_PATH=$(pnpm store path) >> $GITHUB_OUTPUT
    - name: Setup cache
      uses: actions/cache@v3
      id: cache-pnpm-store
      with:
        path: ${{ steps.get-store-path.outputs.STORE_PATH }}
        key: pnpm-store-${{ hashFiles('pnpm-lock.yaml') }}
        restore-keys: |
          pnpm-store-
          pnpm-store-${{ hashFiles('pnpm-lock.yaml') }}
    - name: Install dependencies
      shell: bash
      run: pnpm install
      if: ${{ inputs.skip-install != 'yes' }}
    - name: Run after build
      shell: bash
      run: /bin/bash -c "${{ inputs.after-build }}"
